/**
 * RESERVE - API 엔드포인트 상수
 */

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

export const API_ENDPOINTS = {
    AUTH: {
        LOGIN:       '/api/auth/login',
        LOGOUT:      '/api/auth/logout',
        SIGNUP:      '/api/auth/signup',
        REFRESH:     '/api/auth/refresh',
        ME:          '/api/member/me',
        AGREE_TERMS: '/api/auth/agree-terms',
    },
    EMAIL: {
        SEND_CODE:   '/api/email/send-code',
        VERIFY_CODE: '/api/email/verify-code',
    },
    STORE: {
        LIST:            '/api/stores',
        REGIONS:         '/api/stores/regions',
        DETAIL:          (id) => `/api/stores/${id}`,
        EDIT:            (id) => `/api/stores/${id}/edit`,
        MY_STORES:       '/api/stores/my',
        CREATE:          '/api/stores',
        UPDATE:          (id) => `/api/stores/${id}`,
        DELETE:          (id) => `/api/stores/${id}`,
        ACTIVE_RESERVATIONS_COUNT: (id) => `/api/stores/${id}/active-reservations-count`,
        CLOSURE_READINESS: (id) => `/api/stores/${id}/closure-readiness`,
        AUTO_APPROVAL:   (id) => `/api/stores/${id}/auto-approval`,
        STATISTICS:      (id) => `/api/stores/${id}/statistics`,
    },
    ADDRESS: {
        SEARCH: '/api/address/search',
    },
    HOLIDAY: {
        MONTH: '/api/holidays',
    },
    TOURISM: {
        REGION_PHOTOS: '/api/tourism/region-photos',
        REGION_PHOTO_CATALOG: '/api/tourism/region-photos/catalog',
    },
    RESERVATION: {
        LIST:                '/api/reservations',
        MY_RESERVATIONS:     '/api/reservations/my',
        MY_COMPLETED_FOR_STORE: (storeId) => `/api/reservations/my/store/${storeId}/completed`,
        STORE_RESERVATIONS:  '/api/reservations/store',
        STORE_RESERVATION_SUMMARY: '/api/reservations/store/status-summary',
        CREATE:              '/api/reservations',
        DETAIL:              (id) => `/api/reservations/${id}`,
        UPDATE:              (id) => `/api/reservations/${id}`,
        CANCEL:              (id) => `/api/reservations/${id}/cancel`,
        // 사업자가 확정된 예약을 취소 — CANCEL과 다른 경로다. 그쪽은 예약자 본인만 통과한다(가게는 403).
        STORE_CANCEL:        (id) => `/api/reservations/${id}/store-cancel`,
        REMOVE:              (id) => `/api/reservations/${id}/remove`,
        APPROVE:             (id) => `/api/reservations/${id}/approve`,
        REJECT:              (id) => `/api/reservations/${id}/reject`,
        COMPLETE:            (id) => `/api/reservations/${id}/complete`,
        // 오조작 정정용 Undo — 서버가 10분 이내만 허용한다
        UNDO_APPROVE:        (id) => `/api/reservations/${id}/undo-approve`,
        UNDO_COMPLETE:       (id) => `/api/reservations/${id}/undo-complete`,
        NO_SHOW:             (id) => `/api/reservations/${id}/no-show`,
        AVAILABILITY:        '/api/reservations/availability',
        // 달력용 월 단위 조회 — 날짜마다 상태와 그 사유(휴무/기간밖/마감…)를 함께 준다.
        CALENDAR:            '/api/reservations/calendar',
        QR_TOKEN:            (id) => `/api/reservations/${id}/qr-token`,
        QR_CHECKIN:          '/api/reservations/qr-checkin',
    },
    ADVERTISEMENT: {
        CREATE:          '/api/advertisements',
        PREPARE_PAYMENT: (id) => `/api/advertisements/${id}/prepare-payment`,
        VERIFY_PAYMENT: '/api/advertisements/verify-payment',
        ACTIVE:         '/api/advertisements/active',
        MY_ADS:         '/api/advertisements/my',
        ADMIN_ALL:      '/api/advertisements/admin/all',
        ADMIN_SUSPEND:  (id) => `/api/advertisements/admin/${id}/suspend`,
        CANCEL:         (id) => `/api/advertisements/${id}`,
        // 종료상태 광고 목록에서 숨기기(소프트삭제) — 2026-07 추가
        REMOVE:         (id) => `/api/advertisements/${id}/remove`,
        UPDATE:         (id) => `/api/advertisements/${id}`,
        // 광고 성과 지표(2026-07 추가)
        IMPRESSION:     (id) => `/api/advertisements/${id}/impression`,
        CLICK:          (id) => `/api/advertisements/${id}/click`,
        CONVERSION:     (id) => `/api/advertisements/${id}/conversion`,
    },
    REVIEW: {
        CREATE:          '/api/reviews',
        BY_STORE:        (storeId) => `/api/reviews/store/${storeId}`,
        BY_RESERVATION:  (reservationId) => `/api/reviews/reservation/${reservationId}`,
        CAN_WRITE:       (reservationId) => `/api/reviews/can-write/${reservationId}`,
        MY_REVIEWS:      '/api/reviews/my',
        DETAIL:          (id) => `/api/reviews/${id}`,
        UPDATE:          (id) => `/api/reviews/${id}`,
        DELETE:          (id) => `/api/reviews/${id}`,
    },
    MEMBER: {
        ME:                '/api/member/me',
        UPDATE:            '/api/member/update',
        PASSWORD:          '/api/member/password',
        PROFILE_IMAGE:     '/api/member/profile-image',
        DELETE:            '/api/member/delete',
        WITHDRAWAL_READINESS: '/api/member/withdrawal-readiness',
        MARKETING_CONSENT: '/api/member/me/marketing-consent',
        LOCATION:          '/api/member/me/location',
    },
    BUSINESS: {
        SUBMIT:         '/api/business-verification/submit',
        MY_STATUS:      '/api/business-verification/my-status',
        UPDATE:         '/api/business-verification/update',
        CANCEL:         '/api/business-verification/cancel',
        RESIGN:         '/api/business-verification/resign',
        ADMIN_PENDING:  '/api/business-verification/admin/pending',
        ADMIN_LIST:     '/api/business-verification/admin/list',
        ADMIN_DETAIL:   (id) => `/api/business-verification/admin/${id}`,
        ADMIN_APPROVE:  (id) => `/api/business-verification/admin/${id}/approve`,
        ADMIN_REJECT:   (id) => `/api/business-verification/admin/${id}/reject`,
        ADMIN_REVOKE:   (memberId) => `/api/business-verification/admin/${memberId}/revoke`,
    },
    PAYMENT: {
        STATUS:         '/api/payment/status',
        CONFIG:         '/api/payment/config',
        PREPARE:        '/api/payment/prepare',
        VERIFY:         '/api/payment/verify',
        REFUND:         '/api/payment/refund',
        MY_PAYMENTS:    '/api/payment/my-payments',
        REFUND_PREVIEW: (id) => `/api/payment/refund-preview/${id}`,
    },
    PAYMENT_OPERATIONS: {
        STALE_READY:       '/api/admin/payment-operations/stale-ready',
        RECONCILE_READY:   (id) => `/api/admin/payment-operations/stale-ready/${id}/reconcile`,
        ISSUES:            '/api/admin/payment-operations/issues',
        ISSUE_COUNT:       '/api/admin/payment-operations/issues/open-count',
        WEBHOOKS:          '/api/admin/payment-operations/webhooks',
        WEBHOOK_COUNT:     '/api/admin/payment-operations/webhooks/unfinished-count',
        RETRY_WEBHOOK:     (id) => `/api/admin/payment-operations/webhooks/${id}/retry`,
    },
    PASSWORD_RESET: {
        SEND_CODE:   '/api/password-reset/send-code',
        VERIFY_CODE: '/api/password-reset/verify-code',
        RESET:       '/api/password-reset/reset',
    },
    FAVORITE: {
        TOGGLE: (storeId) => `/api/favorites/toggle/${storeId}`,
        STATUS: (storeId) => `/api/favorites/status/${storeId}`,
        MY:     '/api/favorites/my',
    },
    OAUTH: {
        GOOGLE: '/oauth2/authorization/google',
        NAVER:  '/oauth2/authorization/naver',
        KAKAO:  '/oauth2/authorization/kakao',
    },
    // 통합 메시지. roomId를 받는 폴링·과거 내역·차단·신고는 모두 서버가 참가자를 다시 확인한다.
    CHAT: {
        CONVERSATIONS: '/api/chat/conversations',
        SUPPORT:       '/api/chat/support',
        SUPPORT_SEND:  '/api/chat/support/messages',
        STORE:         (storeId) => `/api/chat/stores/${storeId}`,
        STORE_SEND:    (storeId) => `/api/chat/stores/${storeId}/messages`,
        STORE_INBOX:   '/api/chat/store-inbox',
        STORE_INBOX_ROOM: (roomId) => `/api/chat/store-inbox/${roomId}`,
        STORE_INBOX_SEND: (roomId) => `/api/chat/store-inbox/${roomId}/messages`,
        ROOM_MESSAGES: (roomId) => `/api/chat/rooms/${roomId}/messages`,
        ROOM_HISTORY:  (roomId) => `/api/chat/rooms/${roomId}/history`,
        ROOM_READ:     (roomId) => `/api/chat/rooms/${roomId}/read`,
        ROOM_BLOCK:    (roomId) => `/api/chat/rooms/${roomId}/block`,
        ROOM_REPORTS:  (roomId) => `/api/chat/rooms/${roomId}/reports`,
        UNREAD:        '/api/chat/unread',
        MY:            '/api/chat/my',
        MY_SEND:       '/api/chat/my/messages',
        MY_MESSAGES:   '/api/chat/my/messages',
        MY_UNREAD:     '/api/chat/my/unread',
        ADMIN_ROOMS:   '/api/admin/chat/rooms',
        ADMIN_ROOM:    (id) => `/api/admin/chat/rooms/${id}`,
        ADMIN_POLL:    (id) => `/api/admin/chat/rooms/${id}/messages`,
        ADMIN_REPLY:   (id) => `/api/admin/chat/rooms/${id}/messages`,
        ADMIN_READ:    (id) => `/api/admin/chat/rooms/${id}/read`,
        ADMIN_WAITING: '/api/admin/chat/waiting-count',
        ADMIN_REPORTS: '/api/admin/chat/reports',
        ADMIN_REPORT:  (id) => `/api/admin/chat/reports/${id}`,
        ADMIN_REPORT_CONTEXT: (id) => `/api/admin/chat/reports/${id}/context`,
        // 채팅 첫 안내(인사말 + 자동 문답) — 조회는 로그인 사용자, 저장은 가게 사장님 / 관리자
        INTRO_SUPPORT: '/api/chat/intro/support',
        INTRO_STORE:   (storeId) => `/api/chat/intro/stores/${storeId}`,
        ADMIN_INTRO:   '/api/admin/chat/intro',
        ADMIN_INTRO_AVATAR: '/api/admin/chat/intro/avatar',
    },
    WAITING: {
        BOARD:  (storeId) => `/api/stores/${storeId}/waiting`,
        STATUS: (storeId, entryId) => `/api/stores/${storeId}/waiting/${entryId}/status`,
        STORES: '/api/waiting/stores',
        RETENTION_POLICY: '/api/waiting/retention-policy',
        MY: '/api/waiting/my',
        JOIN: storeId => `/api/waiting/stores/${storeId}/entries`,
        CANCEL: entryId => `/api/waiting/entries/${entryId}/cancel`,
        ENTRY_QR: entryId => `/api/waiting/entries/${entryId}/qr`,
        ONSITE_QR: storeId => `/api/waiting/stores/${storeId}/onsite-qr`,
        CHECKIN: '/api/waiting/qr-checkin',
        EVENTS: '/api/waiting/events',
    },
    MAIL: {
        COMPOSE:      '/api/admin/mail/compose',
        SENT:         '/api/admin/mail/sent',
        // 소프트 삭제(휴지통 이동). 보존 기간이 끝나면 서버 스케줄러가 자동 정리한다.
        TRASH_SENT:   (id) => `/api/admin/mail/sent/${id}`,
    },
    INQUIRY: {
        MY:            '/api/inquiries/my',
        ADMIN_ALL:     '/api/inquiries/admin/all',
        DETAIL:        (id) => `/api/inquiries/${id}`,
        ADMIN_DETAIL:  (id) => `/api/inquiries/admin/${id}`,
        CREATE:        '/api/inquiries',
        DELETE:        (id) => `/api/inquiries/${id}`,
        ADMIN_ANSWER:  (id) => `/api/inquiries/${id}/answer`,
        ADMIN_DELETE:  (id) => `/api/inquiries/admin/${id}`,
        PENDING_COUNT: '/api/inquiries/pending-count',
    },
    TRASH: {
        LIST:    '/api/admin/trash',
        RESTORE: (type, id) => `/api/admin/trash/${type}/${id}/restore`,
    },
    AUDIT_LOG: {
        LIST: '/api/admin/audit-logs',
    },
    ADMIN_MANAGE: {
        MEMBERS:              '/api/admin/manage/members',
        MEMBER_SUSPEND:       (id) => `/api/admin/manage/members/${id}/suspend`,
        MEMBER_BAN:           (id) => `/api/admin/manage/members/${id}/ban`,
        MEMBER_UNBAN:         (id) => `/api/admin/manage/members/${id}/unban`,
        STORES:               '/api/admin/manage/stores',
        STORE_SUSPEND:        (id) => `/api/admin/manage/stores/${id}/suspend`,
        STORE_BAN:            (id) => `/api/admin/manage/stores/${id}/ban`,
        STORE_UNBAN:          (id) => `/api/admin/manage/stores/${id}/unban`,
        RESERVATION_DELETE:   (id) => `/api/admin/manage/reservations/${id}`,
    },
};

export const PUBLIC_STORE_SORT_OPTIONS = [
    { value: 'recommended', label: '추천순' },
    { value: 'rating',      label: '별점순' },
    { value: 'reviewCount', label: '리뷰순' },
    { value: 'distance',    label: '거리순' },
];

export const OWNER_STORE_SORT_OPTIONS = [
    { value: 'recent',      label: '최신 등록순' },
    { value: 'rating',      label: '별점순' },
    { value: 'reviewCount', label: '리뷰순' },
];

// 공개 가게 탐색의 기존 import 호환. 관리자·사업자 화면은 전용 옵션을 사용한다.
export const SORT_OPTIONS = PUBLIC_STORE_SORT_OPTIONS;
