/**
 * RESERVE - API 엔드포인트 상수
 */

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

export const API_ENDPOINTS = {
    AUTH: {
        LOGIN:       '/api/auth/login',
        LOGOUT:      '/api/auth/logout',
        SIGNUP:      '/api/auth/signup',
        REFRESH:     '/api/auth/refresh',
        ME:          '/api/member/me',
        AGREE_TERMS: '/api/auth/agree-terms',
    },
    EMAIL: {
        SEND_CODE:   '/api/email/send-code',
        VERIFY_CODE: '/api/email/verify-code',
    },
    STORE: {
        LIST:            '/api/stores',
        DETAIL:          (id) => `/api/stores/${id}`,
        MY_STORES:       '/api/stores/my',
        CREATE:          '/api/stores',
        UPDATE:          (id) => `/api/stores/${id}`,
        DELETE:          (id) => `/api/stores/${id}`,
        AUTO_APPROVAL:   (id) => `/api/stores/${id}/auto-approval`,
        STATISTICS:      (id) => `/api/stores/${id}/statistics`,
    },
    RESERVATION: {
        LIST:                '/api/reservations',
        MY_RESERVATIONS:     '/api/reservations/my',
        MY_COMPLETED_FOR_STORE: (storeId) => `/api/reservations/my/store/${storeId}/completed`,
        STORE_RESERVATIONS:  '/api/reservations/store',
        CREATE:              '/api/reservations',
        DETAIL:              (id) => `/api/reservations/${id}`,
        UPDATE:              (id) => `/api/reservations/${id}`,
        CANCEL:              (id) => `/api/reservations/${id}/cancel`,
        // 사업자가 확정된 예약을 취소 — CANCEL과 다른 경로다. 그쪽은 예약자 본인만 통과한다(가게는 403).
        STORE_CANCEL:        (id) => `/api/reservations/${id}/store-cancel`,
        REMOVE:              (id) => `/api/reservations/${id}/remove`,
        APPROVE:             (id) => `/api/reservations/${id}/approve`,
        REJECT:              (id) => `/api/reservations/${id}/reject`,
        COMPLETE:            (id) => `/api/reservations/${id}/complete`,
        NO_SHOW:             (id) => `/api/reservations/${id}/no-show`,
        AVAILABILITY:        '/api/reservations/availability',
        QR_TOKEN:            (id) => `/api/reservations/${id}/qr-token`,
        QR_CHECKIN:          '/api/reservations/qr-checkin',
    },
    ADVERTISEMENT: {
        CREATE:          '/api/advertisements',
        PREPARE_PAYMENT: (id) => `/api/advertisements/${id}/prepare-payment`,
        VERIFY_PAYMENT: '/api/advertisements/verify-payment',
        ACTIVE:         '/api/advertisements/active',
        MY_ADS:         '/api/advertisements/my',
        ADMIN_ALL:      '/api/advertisements/admin/all',
        ADMIN_SUSPEND:  (id) => `/api/advertisements/admin/${id}/suspend`,
        CANCEL:         (id) => `/api/advertisements/${id}`,
        // 종료상태 광고 목록에서 숨기기(소프트삭제) — 2026-07 추가
        REMOVE:         (id) => `/api/advertisements/${id}/remove`,
        UPDATE:         (id) => `/api/advertisements/${id}`,
        // 광고 성과 지표(2026-07 추가)
        IMPRESSION:     (id) => `/api/advertisements/${id}/impression`,
        CLICK:          (id) => `/api/advertisements/${id}/click`,
        CONVERSION:     (id) => `/api/advertisements/${id}/conversion`,
    },
    REVIEW: {
        CREATE:          '/api/reviews',
        BY_STORE:        (storeId) => `/api/reviews/store/${storeId}`,
        BY_RESERVATION:  (reservationId) => `/api/reviews/reservation/${reservationId}`,
        CAN_WRITE:       (reservationId) => `/api/reviews/can-write/${reservationId}`,
        MY_REVIEWS:      '/api/reviews/my',
        DETAIL:          (id) => `/api/reviews/${id}`,
        UPDATE:          (id) => `/api/reviews/${id}`,
        DELETE:          (id) => `/api/reviews/${id}`,
    },
    MEMBER: {
        ME:                '/api/member/me',
        UPDATE:            '/api/member/update',
        PROFILE_IMAGE:     '/api/member/profile-image',
        DELETE:            '/api/member/delete',
        MARKETING_CONSENT: '/api/member/me/marketing-consent',
        LOCATION:          '/api/member/me/location',
    },
    BUSINESS: {
        SUBMIT:         '/api/business-verification/submit',
        MY_STATUS:      '/api/business-verification/my-status',
        UPDATE:         '/api/business-verification/update',
        CANCEL:         '/api/business-verification/cancel',
        RESIGN:         '/api/business-verification/resign',
        ADMIN_PENDING:  '/api/business-verification/admin/pending',
        ADMIN_LIST:     '/api/business-verification/admin/list',
        ADMIN_DETAIL:   (id) => `/api/business-verification/admin/${id}`,
        ADMIN_APPROVE:  (id) => `/api/business-verification/admin/${id}/approve`,
        ADMIN_REJECT:   (id) => `/api/business-verification/admin/${id}/reject`,
        ADMIN_REVOKE:   (memberId) => `/api/business-verification/admin/${memberId}/revoke`,
    },
    PAYMENT: {
        CONFIG:         '/api/payment/config',
        PREPARE:        '/api/payment/prepare',
        VERIFY:         '/api/payment/verify',
        REFUND:         '/api/payment/refund',
        MY_PAYMENTS:    '/api/payment/my-payments',
        REFUND_PREVIEW: (id) => `/api/payment/refund-preview/${id}`,
    },
    PASSWORD_RESET: {
        SEND_CODE:   '/api/password-reset/send-code',
        VERIFY_CODE: '/api/password-reset/verify-code',
        RESET:       '/api/password-reset/reset',
    },
    FAVORITE: {
        TOGGLE: (storeId) => `/api/favorites/toggle/${storeId}`,
        STATUS: (storeId) => `/api/favorites/status/${storeId}`,
        MY:     '/api/favorites/my',
    },
    OAUTH: {
        GOOGLE: '/oauth2/authorization/google',
        NAVER:  '/oauth2/authorization/naver',
        KAKAO:  '/oauth2/authorization/kakao',
    },
    MAIL: {
        COMPOSE:      '/api/admin/mail/compose',
        SENT:         '/api/admin/mail/sent',
    },
    INQUIRY: {
        MY:            '/api/inquiries/my',
        ADMIN_ALL:     '/api/inquiries/admin/all',
        DETAIL:        (id) => `/api/inquiries/${id}`,
        ADMIN_DETAIL:  (id) => `/api/inquiries/admin/${id}`,
        CREATE:        '/api/inquiries',
        DELETE:        (id) => `/api/inquiries/${id}`,
        ADMIN_ANSWER:  (id) => `/api/inquiries/${id}/answer`,
        ADMIN_DELETE:  (id) => `/api/inquiries/admin/${id}`,
        PENDING_COUNT: '/api/inquiries/pending-count',
    },
    TRASH: {
        LIST:    '/api/admin/trash',
        RESTORE: (type, id) => `/api/admin/trash/${type}/${id}/restore`,
        DELETE:  (type, id) => `/api/admin/trash/${type}/${id}`,
    },
    AUDIT_LOG: {
        LIST: '/api/admin/audit-logs',
    },
    ADMIN_MANAGE: {
        MEMBERS:              '/api/admin/manage/members',
        MEMBER_SUSPEND:       (id) => `/api/admin/manage/members/${id}/suspend`,
        MEMBER_BAN:           (id) => `/api/admin/manage/members/${id}/ban`,
        MEMBER_UNBAN:         (id) => `/api/admin/manage/members/${id}/unban`,
        STORES:               '/api/admin/manage/stores',
        STORE_SUSPEND:        (id) => `/api/admin/manage/stores/${id}/suspend`,
        STORE_BAN:            (id) => `/api/admin/manage/stores/${id}/ban`,
        STORE_UNBAN:          (id) => `/api/admin/manage/stores/${id}/unban`,
        RESERVATION_DELETE:   (id) => `/api/admin/manage/reservations/${id}`,
    },
};

export const SORT_OPTIONS = [
    { value: 'rating',      label: '별점순' },
    { value: 'reviewCount', label: '리뷰순' },
    { value: 'name',        label: '이름순' },
    { value: 'distance',    label: '거리순' },
];
