spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

jwt:
  secret-key: ${JWT_SECRET_KEY}

mail:
  username: resend
  password: ${RESEND_API_KEY}

portone:
  imp-key: ${PORTONE_IMP_KEY}
  imp-secret: ${PORTONE_IMP_SECRET}
  imp-code: ${PORTONE_IMP_CODE}
  v2-secret: ${PORTONE_V2_SECRET}
  store-id: ${PORTONE_STORE_ID}

# AWS S3
S3_BUCKET_NAME: reserve-it-kr-bucket
CLOUDFRONT_DOMAIN: cdn.reserve.it.kr
AWS_REGION: ap-northeast-2
AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
